# The name of the step just as a reference.
name: "mdl and Python style checks"
description: "This check will run several scripts to ensure the formatting."
author: "jmerritt@esri.com"

inputs:
  FILE_PATHS:
    description: "Files to run the checks on."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "-s"
    - ${{ inputs.FILE_PATHS }}

branding:
  icon: "mic"
  color: "purple"
